/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
        },
        surface: {
          DEFAULT: '#0f172a',
          muted: '#1e293b',
          border: '#334155',
        },
        /* Bảng màu giao diện đăng nhập (Material / glacier) */
        background: '#0a0e1a',
        'surface-dim': '#0f1524',
        'surface-bright': '#1a2438',
        'surface-variant': '#1a2438',
        'surface-container': '#141c2e',
        'surface-container-low': '#111828',
        'surface-container-lowest': '#0a0e1a',
        'surface-container-high': '#1a2438',
        'surface-container-highest': '#202c42',
        primary: '#7dd3fc',
        'primary-container': '#0e4d6e',
        'primary-fixed': '#c8eaff',
        'primary-fixed-dim': '#7dd3fc',
        'on-primary': '#001f2e',
        'on-primary-container': '#c8eaff',
        'on-primary-fixed': '#001f2e',
        'on-primary-fixed-variant': '#004d73',
        secondary: '#88b4cc',
        'secondary-container': '#1a3a4e',
        'secondary-fixed': '#c0d8e8',
        'secondary-fixed-dim': '#88b4cc',
        'on-secondary': '#001f2e',
        'on-secondary-container': '#c0d8e8',
        'on-secondary-fixed': '#0d1f2b',
        'on-secondary-fixed-variant': '#2a4a5e',
        tertiary: '#c8a0f0',
        'tertiary-container': '#3d2060',
        'tertiary-fixed': '#e8d0ff',
        'tertiary-fixed-dim': '#c8a0f0',
        'on-tertiary': '#1a002e',
        'on-tertiary-container': '#e8d0ff',
        'on-tertiary-fixed': '#1a002e',
        'on-tertiary-fixed-variant': '#4d2a73',
        error: '#ff6b6b',
        'error-container': '#3d1414',
        'on-error': '#1a0000',
        'on-error-container': '#ffb3b3',
        outline: '#4a6070',
        'outline-variant': '#2a3a48',
        'on-background': '#e0e8f0',
        'on-surface': '#e0e8f0',
        'on-surface-variant': '#a0b4c4',
        'surface-tint': '#7dd3fc',
        'inverse-surface': '#e0e8f0',
        'inverse-on-surface': '#0a0e1a',
        'inverse-primary': '#0a4c6e',
      },
      fontFamily: {
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
        display: ['Outfit', 'system-ui', 'sans-serif'],
        glacier: ['Inter', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        glacier: '0.5rem',
        'glacier-lg': '1rem',
        'glacier-xl': '1.5rem',
      },
    },
  },
  plugins: [],
};
